FROM hexpm/elixir:1.12.3-erlang-24.1.7-debian-bullseye-20210902-slim

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential curl inotify-tools git

# For nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
RUN apt-get install -y nodejs && apt-get clean && rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV=dev
ENV NODE_ENV=development

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY assets/package.json assets/package-lock.json /app/assets/
RUN npm install --prefix ./assets

WORKDIR /app

CMD ["mix", "phx.server"]
